### ISSUE TITLE
作者看下

### ISSUE THREAD

**Issue by xiazaidian02** [ba0gu0/520apkhook#46]
520ApkHook.zipalign.signer.apk
只要安装这个是吧 那生成的证书不用管 我还是不知道为什么后面那个apk 要加./
我已经加了还是不行 还买了个安卓6.0手机 还是不行
你检查下是不是你写错JAVA了
我在应用信息里看了下 不论是手机还是雷电模拟器
生成的APP都没获取任何权限 在手机上如果手动赋予他权限
生成的程序最新版支付宝都能运行 雷电模拟器没法赋予权限运行
你检查下是不是生成的APP没赋予权限的问题

但是远控是附加的没法赋予权限所以也不运行在手机上只能支付宝运行就是手动赋予权限

**Comment by sagatneed** [comment]
兄弟我有个问题，就是你将合成后的apk放到雷电模拟器时候，你安装成功后能打开app吗？

**Comment by MAO-qi** [comment]
> 兄弟我有个问题，就是你将合成后的apk放到雷电模拟器时候，你安装成功后能打开app吗？

我也不行，不管是模拟器还是真机都运行不了直接闪退
