### ISSUE TITLE
搭配AhMyth使用，AhMyth无法检测到设备，同一端口

### ISSUE THREAD

**Issue by SuiranQaQ** [ba0gu0/520apkhook#47]
设备安装apk后，Metasploit 可以检测到设备和使用命令，但是AhMyth无法检测，是哪里操作存在问题吗
![image](https://github.com/ba0gu0/520apkhook/assets/97267668/a8061cf9-6077-426e-8f8a-015f754a0cff)

**Comment by SuiranQaQ** [comment]
是要在注入的时候应该选择注入的是Ahmyth生成的APK，而不是现在msfvenom生成出来的msf.apk
java -jar C:\path\to\a520ApkHook-1.2.1-jar-with-dependencies.jar -o C:\Users\Administrator\Downloads\合法App.apk C:\Users\Administrator\Downloads\msf.apk

**Comment by ba0gu0** [comment]
> 设备安装apk后，Metasploit 可以检测到设备和使用命令，但是AhMyth无法检测，是哪里操作存在问题吗
> 
> ![image](https://github.com/ba0gu0/520apkhook/assets/97267668/a8061cf9-6077-426e-8f8a-015f754a0cff)
> 
> 

msf的payload应该没啥问题。

目前ahmyth好像有问题，为了过杀软，所以把远控生成的包进行了修改，把包名改了。

改包名之后，ahmyth直接运行可以上线，但是注入到apk里面就不行了。

不修改包名注入是可以正常上线的，还在排查原因。
看了ahmyth的安卓源码，也没找到问题。。。

msf就没这个问题，原始的可以上线，改包名可以上线，改完包名注入后还可以上线。

workdir目录下，有一个bypass.apk，就是改完包名的，完全没问题，注入后就有问题了，用msf就没问题。

抽空再研究研究吧。

**Comment by SuiranQaQ** [comment]
好的，谢谢作者大大，现在ahmyth这两天研究下来是没什么太大问题了，但是ahmyth-plus那个版本又出问题，就有点头大，plus版本要获取一个设备管理员权限啥的

**Comment by SuiranQaQ** [comment]
![image](https://github.com/user-attachments/assets/c86b3074-0f84-4c3d-964c-5838265c1b89)
被注入的APP正常运行，但是并没有获取权限和设备管理者那些引导 ，远控不显示设备，我尝试加过 -o 也没用，这是不注入正常APP直接安装远控之后的执行，是正常可用的
![image](https://github.com/user-attachments/assets/7e44ac2d-f97a-4f98-9673-c42bc51b51a5)
![image](https://github.com/user-attachments/assets/17fd33de-1aae-4a7a-8165-70d545bac07a)

**Comment by SuiranQaQ** [comment]
这是对应的项目地址 https://github.com/VenomDino/AhMyth-Plus
