### ISSUE TITLE
安卓生成后门添加参数

### ISSUE THREAD

**Issue by RookieTerry** [ba0gu0/520apkhook#5]
大佬您好，请问怎么在生成木马时自动添加`sessioncommunicationtimeout=0`和`sessionexpirationtimeout=0`这两项参数啊？看了您的源码，还是不太明白从哪里入手修改

**Comment by ba0gu0** [comment]
修改的msf原版的安卓远控dex文件，参考msf源码里面修改dex文件的代码。
https://raw.githubusercontent.com/ba0gu0/520apkhook/master/libs/MsfDexDir/classes.dex
参考这个里面代码分析
https://raw.githubusercontent.com/ba0gu0/520apkhook/master/utils/CreateMsfDex.py

**Comment by RookieTerry** [comment]
还没添加参数，为什么生成的apk文件甚至都安装不了？
