### ISSUE TITLE
作者您好，请问一下我这个是什么问题

### ISSUE THREAD

**Issue by ichengps** [ba0gu0/520apkhook#50]
读取meta信息失败
![IMG_20240814_213653](https://github.com/user-attachments/assets/76e37999-9a97-4422-9913-eac570397fcf)
请问是我的操作有问题还是某个地方配置的不对

**Comment by ba0gu0** [comment]
可能是被注入的apk进行了安全加固（静态文件层面），读取app信息失败。换个app注入

**Comment by ichengps** [comment]
好的

**Comment by ichengps** [comment]
您好，还是不行。 是不是我的java版本不对，我用的是17

**Comment by ba0gu0** [comment]
操作系统类型是？还有系统架构

**Comment by ichengps** [comment]
Ubuntu arm64

**Comment by ba0gu0** [comment]
那个没准备arm版本的，只放了x64的。

这几个文件，每次执行的时候会释放，目前只放了64为的Linux

<img width="879" alt="image" src="https://github.com/user-attachments/assets/2d357cb9-357d-4ac4-82bf-6293f15a38e7">

推荐在win11 虚拟机里面运行，虽然也是arm的，但是兼容。

**Comment by ichengps** [comment]
好的，谢谢您

**Comment by ichengps** [comment]
好的谢谢您

**Comment by sagatneed** [comment]
> 好的，谢谢您

你好，请问你的问题解决了吗
