### ISSUE TITLE
求大佬们帮我指出问题

### ISSUE THREAD

**Issue by Xalsace** [ba0gu0/520apkhook#51]
创建木马时我是用的是我本机ip端口是1433后来注入软件一切正常
![Snipaste_2024-08-19_18-30-49](https://github.com/user-attachments/assets/81ec709e-0e10-4cd0-a2f9-339212e14273)
安装到手机上后手动给予了所有权限但msf提示有一个job但是没有创建session咋搞啊

**Comment by sagatneed** [comment]
兄弟我有个问题，你这个正常的app包是从哪里来的，为什么我利用520apkhook将msf生成的木马apk与原来的app包合成显示成功，但是放在模拟器里面却失败了

**Comment by sagatneed** [comment]
而且你发出来的这个代码，显示你监听的设备压根就没上线，没监测到设备上线的原因大概是因为网不通，你肯定没有设置公网ip，默认路由器分配给你的ip地址是局域网保留地址，与你监测设备不在一个网段没法通信，所以你肯定监测不到。

**Comment by MAO-qi** [comment]
> 创建木马时我是用的是我本机ip端口是1433后来注入软件一切正常 ![Snipaste_2024-08-19_18-30-49](https://private-user-images.githubusercontent.com/119861958/359072229-81ec709e-0e10-4cd0-a2f9-339212e14273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDU0MTEsIm5iZiI6MTcyNTYwNTExMSwicGF0aCI6Ii8xMTk4NjE5NTgvMzU5MDcyMjI5LTgxZWM3MDllLTBlMTAtNGNkMC1hMmY5LTMzOTIxMmUxNDI3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwNjQ1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGNlY2MwODI1NGQ4M2NiODA4NWFiZjg1MTc4YWQ4YzU4NzA0YjM0MDJiNGI2YmNkM2NhZjI3MjNlOTQ4MDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rluMGnWzt2vzvsgqQM0ZluzNdKDibuySizD5LrnCOXs) 安装到手机上后手动给予了所有权限但msf提示有一个job但是没有创建session咋搞啊

兄弟为啥我合成的app运行不了哇
